name: Release VSCode Extension
run-name: packaging
on:
  push:
    tags:
      - v*
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm i
      - run: npm i -g @vscode/vsce
      - run: vsce package
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            vscode-vrm*.vsix